### ISSUE TITLE
Rewrite in `stencil`?

### ISSUE THREAD

**Issue by baseplate-admin** [coreproject-moe/icons#10]
Check this :

For `svelte` + `sveltekit`:
* https://github.com/sveltejs/kit/issues/2666#issuecomment-1384211849

For NextJS (Not Supported):
* https://github.com/ionic-team/stencil/issues/4389#issue-1710808584

**Comment by christian-bromann** [comment]
Hey @baseplate-admin 👋  just letting you know that we are working on Next.js support for Stencil and hope to deliver this within the next weeks.

**Comment by baseplate-admin** [comment]
> Hey @baseplate-admin 👋 just letting you know that we are working on Next.js support for Stencil and hope to deliver this within the next weeks.

That's awesome. (also thank you for noticing such a small project).
