### ISSUE TITLE
Get this moving?

### ISSUE THREAD

**Issue by baseplate-admin** [coreproject-moe/icons#63]
So we have 2 choices right now.

- Lit
- Stencil

But both approaches don't support tailwind to style svg.

We have to figure out
- CSS injection
- Limited styling API ( but highly customizable )
- No SSR for web-component, meaning FOUC while the bundle loads ( which is not half bad imho )

**Comment by moonlitgrace** [comment]
> But both approaches don't support tailwind to style svg.

they dont? uh cant we just pass `class` as a `prop` or something?

**Comment by baseplate-admin** [comment]
> they dont? uh cant we just pass class as a prop or something?

Nope. It Won't work

**Comment by baseplate-admin** [comment]
> they dont? uh cant we just pass class as a prop or something?

This is because we are using [shadow dom](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM). This means the SVG's css cannot access main css file

**Comment by moonlitgrace** [comment]
> This means the SVG's css cannot access main css file

Then a wrapper or something? if we cant access main svg element we cant do some styles such as `stroke`, `fill`... etc like `SVGAttributes`?
